# Generated by Django 4.1.7 on 2023-03-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0006_telegramuser_wbtoken_alter_telegramuser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierId', models.CharField(max_length=255, verbose_name='ID продавца')),
                ('oldId', models.IntegerField(verbose_name='Старый ID продавца')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('full_name', models.TextField(verbose_name='Полное наименование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'Кабинет WB',
                'verbose_name_plural': 'Кабинеты WB',
            },
        ),
        migrations.CreateModel(
            name='TrackedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmId', models.CharField(max_length=20, verbose_name='Артикул WB')),
                ('vendorCode', models.CharField(max_length=255, verbose_name='Артикул')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.personal', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Отслеживаемый артикул',
                'verbose_name_plural': 'Отслеживаемые артикулы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.CharField(max_length=255, verbose_name='WB ID')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('stars', models.SmallIntegerField(verbose_name='Кол-во звезд')),
                ('created_date', models.DateTimeField(verbose_name='Дата отзыва на WB')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.trackedarticle', verbose_name='Артикул')),
            ],
            options={
                'verbose_name': 'Отзыв об артикуле',
                'verbose_name_plural': 'Отзывы об артикуле',
            },
        ),
    ]
