# Generated by Django 4.1.7 on 2023-03-07 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_trackedarticle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка на фото')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.feedback', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Фотография отзыва',
                'verbose_name_plural': 'Фотографии отзывов',
            },
        ),
    ]
