# Generated by Django 4.1.7 on 2023-03-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_personal_sheetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='sheetId',
            field=models.IntegerField(default=None, null=True, verbose_name='ID листа'),
        ),
    ]
