# Generated by Django 4.1.7 on 2023-03-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_personal_sheetid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='sheetId',
        ),
    ]
