# Generated by Django 4.1.7 on 2023-03-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Username(@)')),
                ('user_id', models.CharField(default=None, max_length=30, unique=True, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Phone number')),
                ('unactive', models.BooleanField(default=False, verbose_name='Does user blocked bot?')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
    ]
