# Generated by Django 4.1.7 on 2023-03-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='unactive',
            field=models.BooleanField(default=False, verbose_name='Does user block bot?'),
        ),
    ]
