# Generated by Django 4.1.7 on 2023-03-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_telegramuser_unactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'telegram user', 'verbose_name_plural': 'telegram users'},
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='unactive',
            field=models.BooleanField(default=False, verbose_name='does user block bot?'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.CharField(default=None, max_length=30, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='username'),
        ),
    ]
