# Generated by Django 4.1.7 on 2023-03-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_telegramuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Пользователь телеграмма', 'verbose_name_plural': 'Пользователи телеграмма'},
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='unactive',
            field=models.BooleanField(default=False, verbose_name='Пользователь заблокировал бота?'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.CharField(default=None, max_length=30, unique=True, verbose_name='ИД'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя пользователя'),
        ),
    ]
