# Generated by Django 4.1.7 on 2023-03-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_telegramuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='WBToken',
            field=models.TextField(default=None, null=True, verbose_name='WBToken'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='ИД'),
        ),
    ]
