# Generated by Django 4.1.7 on 2023-03-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_telegramuser_wbtoken_alter_telegramuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='temp_token',
            field=models.TextField(default=None, null=True, verbose_name='Временный токен для авторизации'),
        ),
    ]
