# Generated by Django 4.1.7 on 2023-03-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_telegramuser_temp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='notification',
            field=models.BooleanField(default=True, verbose_name='Уведомления включены?'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='notification_stars',
            field=models.SmallIntegerField(default=5, verbose_name='Кол-во звезд для уведомлений'),
        ),
    ]
